### ISSUE TITLE
Command Option Support

### ISSUE THREAD

**Issue by ghost1372** [1217950746/Arthas-WPFUI#2]
hi please add command binding option to this controls 
for example in wpf default button wa have:
<Button Command="{Binding LoginCommand}" Content="Button" </Button>
but in Arthas Controls None of them have this feature.

**Comment by oneo-me** [comment]
MetroButton based on Button

**Comment by ghost1372** [comment]
i used this code and added Support Command Property if you want i can make a pull reqeast i added this to all of controls and its work fine.
```
public static DependencyProperty ReloadCommandProperty
= DependencyProperty.Register(
    "ReloadCommand",
    typeof(ICommand),
    typeof(MetroButton));

        public static DependencyProperty SaveCommandProperty
            = DependencyProperty.Register(
                "SaveCommand",
                typeof(ICommand),
                typeof(MetroButton));

        public ICommand ReloadCommand
        {
            get
            {
                return (ICommand)GetValue(ReloadCommandProperty);
            }

            set
            {
                SetValue(ReloadCommandProperty, value);
            }
        }

        public ICommand SaveCommand
        {
            get
            {
                return (ICommand)GetValue(SaveCommandProperty);
            }

            set
            {
                SetValue(SaveCommandProperty, value);
            }
        }
    }
```

**Comment by oneo-me** [comment]
Modify MetroButton.cs
MetroButton: ButtonBase
for
MetroButton: Button

English is not good, Google translation

**Comment by ghost1372** [comment]
i know, i fixed this issue, do you want i make a pull request for you?

**Comment by oneo-me** [comment]
You can Fork this project, README has been written, not updated

**Comment by ghost1372** [comment]
tnx This is a great library Please support it and add more and better controls

**Comment by oneo-me** [comment]
This project is open source at the request of friends, I currently work mainly with the macOS platform, and this project is too old, I have the opportunity to open another source for the same project
