### ISSUE TITLE
在VS2017环境中无法打开解决方案

### ISSUE THREAD

**Issue by NickNameIsNull** [1217950746/Arthas-WPFUI#7]
我将代码下载下来过后，用VS2017打开项目，VS提示“项目文件不完整。缺少预期导入";
是因为我电脑上没有安装.net core 3.0 SDK的原因吗？
在半年之前我从GitHub上下载的代码是能打开的。

**Comment by ghost1372** [comment]
yes you need net core 3 sdk 
also you need vs2019
download here
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe
https://github.com/dotnet/core-sdk

**Comment by NickNameIsNull** [comment]
> yes you need net core 3 sdk
> also you need vs2019
> download here
> [https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe ](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe)
> [https://github.com/dotnet/core-sdk](https://github.com/dotnet/core-sdk)

我通过你提供的.net core3下载链接 安装了.net core3.0.1 pre5 的sdk；也安装了最新的vs2019，但是还是无法打开项目，打开项目VS2019提示："Sdk未找到。检查是否安装了最新的. net Core SDK，或增加global.json中指定的版本"。 对话框中的详细信息指向了一个 \dotnet\sdk\2.2.202\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk的路径，是还有什么依赖的SDK需要安装吗？

**Comment by NickNameIsNull** [comment]
OK,The problem has been solved.
fist:you need net core 3 sdk;
secondly:also need vs2019;
If the problem can't be solved,you need in solution path add 'global.json' file,file content is as follows:
`{
    "sdk": {
        "version": "3.0.100-preview5"
    }
}`
Specify the version of .net core sdk.
渣渣英语，想表达的意思如下：
这个问题的解决方法是：
1.首先你需要有.net core3 的 sdk
2.其次你需要安装有vs2019
如果上述环境你都具备了，问题依然未解决，需要在解决方案的目录下添加 global.json 文件，文件的内容如下：
`{
    "sdk": {
        "version": "3.0.100-preview5"
    }
}`
此文件的作用是指定.net core sdk的版本。（我是这么理解的，若有误，请指正。）
thx.

**Comment by ghost1372** [comment]
Tnx bro, if you intresting in wpf controls there is a better project that is active and complete, see here
Https://github.com/handyorg/handycontrol
Arthas project is dead

**Comment by oneo-me** [comment]
需要VS2019预览版，.Net Core 3.0 预览版

VS2017需要手动修改项目文件
